package repositories

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
	"pay-chain.backend/internal/domain/entities"
	domainerrors "pay-chain.backend/internal/domain/errors"
	"pay-chain.backend/internal/infrastructure/models"
)

type ApiKeyRepository struct {
	db *gorm.DB
}

func NewApiKeyRepository(db *gorm.DB) *ApiKeyRepository {
	return &ApiKeyRepository{db: db}
}

func (r *ApiKeyRepository) Create(ctx context.Context, apiKey *entities.ApiKey) error {
	m := r.toModel(apiKey)
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		return err
	}
	// Update ID in case it was generated by DB (though we usually generate i in Usecase or Entity default)
	apiKey.ID = m.ID
	return nil
}

func (r *ApiKeyRepository) FindByKeyHash(ctx context.Context, keyHash string) (*entities.ApiKey, error) {
	var m models.ApiKey
	if err := r.db.WithContext(ctx).Preload("User").Where("key_hash = ?", keyHash).First(&m).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domainerrors.ErrNotFound
		}
		return nil, err
	}
	return r.toEntity(&m), nil
}

func (r *ApiKeyRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]*entities.ApiKey, error) {
	var ms []models.ApiKey
	if err := r.db.WithContext(ctx).Where("user_id = ?", userID).Find(&ms).Error; err != nil {
		return nil, err
	}
	var result []*entities.ApiKey
	for _, m := range ms {
		// Use a local copy to avoid referencing the same variable
		model := m
		result = append(result, r.toEntity(&model))
	}
	return result, nil
}

func (r *ApiKeyRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.ApiKey, error) {
	var m models.ApiKey
	if err := r.db.WithContext(ctx).Where("id = ?", id).First(&m).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, domainerrors.ErrNotFound
		}
		return nil, err
	}
	return r.toEntity(&m), nil
}

func (r *ApiKeyRepository) Update(ctx context.Context, apiKey *entities.ApiKey) error {
	m := r.toModel(apiKey)
	result := r.db.WithContext(ctx).Model(&models.ApiKey{}).Where("id = ?", apiKey.ID).Updates(map[string]interface{}{
		"name":             m.Name,
		"permissions":      m.Permissions,
		"is_active":        m.IsActive,
		"last_used_at":     m.LastUsedAt,
		"updated_at":       time.Now(),
		"secret_encrypted": m.SecretEncrypted,
		"secret_masked":    m.SecretMasked,
	})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return domainerrors.ErrNotFound
	}
	return nil
}

func (r *ApiKeyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	result := r.db.WithContext(ctx).Delete(&models.ApiKey{}, "id = ?", id)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return domainerrors.ErrNotFound
	}
	return nil
}

// Helper Mappers

func (r *ApiKeyRepository) toModel(e *entities.ApiKey) *models.ApiKey {
	m := &models.ApiKey{
		ID:              e.ID,
		UserID:          e.UserID,
		Name:            e.Name,
		KeyPrefix:       e.KeyPrefix,
		KeyHash:         e.KeyHash,
		SecretEncrypted: e.SecretEncrypted,
		SecretMasked:    e.SecretMasked,
		Permissions:     "", // Set below
		IsActive:        e.IsActive,
		LastUsedAt:      e.LastUsedAt,
		ExpiresAt:       e.ExpiresAt,
		CreatedAt:       e.CreatedAt,
		UpdatedAt:       e.UpdatedAt,
	}
	permissionsBytes, _ := json.Marshal(e.Permissions)
	m.Permissions = string(permissionsBytes)
	// DeletedAt is handled by GORM
	return m
}

func (r *ApiKeyRepository) toEntity(m *models.ApiKey) *entities.ApiKey {
	e := &entities.ApiKey{
		ID:              m.ID,
		UserID:          m.UserID,
		Name:            m.Name,
		KeyPrefix:       m.KeyPrefix,
		KeyHash:         m.KeyHash,
		SecretEncrypted: m.SecretEncrypted,
		SecretMasked:    m.SecretMasked,
		Permissions:     []string{}, // Set below
		IsActive:        m.IsActive,
		LastUsedAt:      m.LastUsedAt,
		ExpiresAt:       m.ExpiresAt,
		CreatedAt:       m.CreatedAt,
		UpdatedAt:       m.UpdatedAt,
	}

	_ = json.Unmarshal([]byte(m.Permissions), &e.Permissions)

	if m.User.ID != uuid.Nil {
		e.User = &entities.User{
			ID:        m.User.ID,
			Email:     m.User.Email,
			Name:      m.User.Name,
			Role:      entities.UserRole(m.User.Role),
			KYCStatus: entities.KYCStatus(m.User.KYCStatus),
			CreatedAt: m.User.CreatedAt,
			UpdatedAt: m.User.UpdatedAt,
		}
	}

	return e
}
