-- 000005_seed_smart_contracts.up.sql

-- =========================
-- Seed Chains
-- =========================
INSERT INTO chains (id, namespace, name, chain_type, rpc_url, explorer_url, is_active)
VALUES
  (11155111, 'eip155', 'Sepolia', 'EVM', 'https://1rpc.io/sepolia', 'https://sepolia.etherscan.io', true),
  (103, 'solana', 'Solana Devnet', 'SVM', 'https://api.devnet.solana.com', 'https://explorer.solana.com/?cluster=devnet', true)
ON CONFLICT (id) DO NOTHING;

-- =========================
-- Seed Smart Contracts
-- =========================
-- NOTE:
-- - id generated by DEFAULT (UUID from app / DB default)
-- - chain_id MUST match chains.id
-- - ABI explicitly cast to jsonb

-- Sepolia
INSERT INTO smart_contracts (
  chain_id,
  contract_address,
  name,
  type,
  version,
  deployer_address,
  is_active,
  abi
)
VALUES
  (11155111, '0x7b79995e5f793a07bc00c21412e50ecae098e7f9', 'Sepolia Gateway', 'GATEWAY', '1.0.0', '0x1234567890123456789012345678901234567890', true, '{}'::jsonb),
  (11155111, '0x7b79995e5f793a07bc00c21412e50ecae098e7fa', 'Sepolia Router', 'ROUTER', '1.0.0', '0x1234567890123456789012345678901234567890', true, '{}'::jsonb),
  (11155111, '0x7b79995e5f793a07bc00c21412e50ecae098e7fb', 'Sepolia TokenRegistry', 'TOKEN_REGISTRY', '1.0.0', '0x1234567890123456789012345678901234567890', true, '{}'::jsonb)
ON CONFLICT (chain_id, contract_address) DO NOTHING;

-- Solana Devnet
INSERT INTO smart_contracts (
  chain_id,
  contract_address,
  name,
  type,
  version,
  deployer_address,
  is_active,
  abi
)
VALUES
  (103, 'PayChainGatewayProgramID11111111111111111', 'Solana Gateway', 'GATEWAY', '1.0.0', 'Deployer...', true, '{}'::jsonb)
ON CONFLICT (chain_id, contract_address) DO NOTHING;
