-- Unify Hyperbridge contract types into a single ADAPTER_HYPERBRIDGE type
UPDATE smart_contracts 
SET type = 'ADAPTER_HYPERBRIDGE' 
WHERE type IN ('HYPERBRIDGE_TOKEN_GATEWAY', 'ADAPTER_HYPERBRIDGE_TOKEN_SENDER', 'ADAPTER_HYPERBRIDGE_TOKEN_RECEIVER');
