ALTER TABLE payments
ADD COLUMN is_rescued BOOLEAN DEFAULT FALSE,
ADD COLUMN rescued_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN retry_count INTEGER DEFAULT 0,
ADD COLUMN last_retry_at TIMESTAMP WITH TIME ZONE;
